package core.uievents;

public enum UIEventType {
    PROJECT_OPENED, FILE_OPENED_FOR_EDIT, CLASS_STRUCTURE_NODE_CLICKED, FILE_REMOVED_FROM_PROJECT, PROJECT_STRUCTURE_CHANGED,
    FILENAME_CHANGED, DIALOG_CLOSE_REQUEST, DIALOG_ACCEPT_REQUEST
}
